# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# This file is the device-specific product definition file for
# smdkv310. It lists all the overlays, files, modules and properties
# that are specific to this hardware: i.e. those are device-specific
# drivers, configuration files, settings, etc...

# Note that smdkv310 is not a fully open device. Some of the drivers
# aren't publicly available in all circumstances, which means that some
# of the hardware capabilities aren't present in builds where those
# drivers aren't available. Such cases are handled by having this file
# separated into two halves: this half here contains the parts that
# are available to everyone, while another half in the vendor/ hierarchy
# augments that set with the parts that are only relevant when all the
# associated drivers are available. Aspects that are irrelevant but
# harmless in no-driver builds should be kept here for simplicity and
# transparency. There are two variants of the half that deals with
# the unavailable drivers: one is directly checked into the unreleased
# vendor tree and is used by engineers who have access to it. The other
# is generated by setup-makefile.sh in the same directory as this files,
# and is used by people who have access to binary versions of the drivers
# but not to the original vendor tree. Be sure to update both.



# These is the hardware-specific overlay, which points to the location
# of hardware-specific resource overrides, typically the frameworks and
# application settings that are stored in resourced.

LOCAL_PATH := device/samsung/smdkv310

PRODUCT_COMMON_DIR := device/samsung/common/exynos4

include $(LOCAL_PATH)/BoardConfig.mk

DEVICE_PACKAGE_OVERLAYS := $(LOCAL_PATH)/overlay

ifeq ($(BOARD_USES_HGL),true)
PRODUCT_COPY_FILES += \
	device/samsung/smdkv310/conf/egl.cfg:system/lib/egl/egl.cfg \
	$(PRODUCT_COMMON_DIR)/lib/mali_ump/libEGL_mali.so:system/lib/egl/libEGL_mali.so \
	$(PRODUCT_COMMON_DIR)/lib/mali_ump/libGLESv1_CM_mali.so:system/lib/egl/libGLESv1_CM_mali.so \
	$(PRODUCT_COMMON_DIR)/lib/mali_ump/libGLESv2_mali.so:system/lib/egl/libGLESv2_mali.so \
	$(PRODUCT_COMMON_DIR)/lib/mali_ump/libMali.so:system/lib/libMali.so \
	$(PRODUCT_COMMON_DIR)/lib/mali_ump/libMali.so:obj/lib/libMali.so \
	$(PRODUCT_COMMON_DIR)/lib/mali_ump/libUMP.so:system/lib/libUMP.so \
	$(PRODUCT_COMMON_DIR)/lib/mali_ump/libUMP.so:obj/lib/libUMP.so \
	$(PRODUCT_COMMON_DIR)/lib/mali_ump/libion.so:system/lib/libion.so \
	$(PRODUCT_COMMON_DIR)/lib/mali_ump/libion.so:obj/lib/libion.so
endif

# Init files
PRODUCT_COPY_FILES += \
	$(LOCAL_PATH)/conf/init.smdkc210.rc:root/init.smdkc210.rc \
	$(LOCAL_PATH)/conf/init.smdkc210.usb.rc:root/init.smdkc210.usb.rc \
	$(LOCAL_PATH)/conf/ueventd.smdkc210.rc:root/ueventd.smdkc210.rc \
	$(LOCAL_PATH)/conf/init.smdkv310.rc:root/init.smdkv310.rc \
	$(LOCAL_PATH)/conf/init.smdkv310.usb.rc:root/init.smdkv310.usb.rc \
	$(LOCAL_PATH)/conf/ueventd.smdkv310.rc:root/ueventd.smdkv310.rc

# Prebuilt kl keymaps
PRODUCT_COPY_FILES += \
	$(LOCAL_PATH)/samsung-keypad.kl:system/usr/keylayout/samsung-keypad.kl

# Generated kcm keymaps
PRODUCT_PACKAGES := \
	samsung-keypad.kcm

# Filesystem management tools
PRODUCT_PACKAGES += \
	make_ext4fs \
	setup_fs

# audio
PRODUCT_PACKAGES += \
	audio_policy.smdkv310 \
	audio.primary.smdkv310 \
	audio.a2dp.default \
	libaudioutils

# Camera
PRODUCT_PACKAGES += \
	camera.smdkv310

# Libs
PRODUCT_PACKAGES += \
	libcamera \
	libstagefrighthw \
	com.android.future.usb.accessory

# Video Editor
PRODUCT_PACKAGES += \
	VideoEditorGoogle

# Misc other modules
PRODUCT_PACKAGES += \
	lights.smdkv310 \
	hwcomposer.exynos4

# OpenMAX IL configuration files
PRODUCT_COPY_FILES += \
	$(PRODUCT_COMMON_DIR)/multimedia/openmax/core/secomxregistry:system/etc/secomxregistry \
	$(LOCAL_PATH)/media_profiles.xml:system/etc/media_profiles.xml

# OpenMAX IL modules
PRODUCT_PACKAGES += \
	libSEC_OMX_Core \
	libSEC_Resourcemanager \
	libOMX.SEC.AVC.Decoder \
	libOMX.SEC.M4V.Decoder \
	libOMX.SEC.M4V.Encoder \
	libOMX.SEC.AVC.Encoder

# MFC firmware
PRODUCT_COPY_FILES += \
	$(PRODUCT_COMMON_DIR)/firmware/mfc_fw.bin:root/vendor/firmware/mfc_fw.bin

# Input device calibration files
PRODUCT_COPY_FILES += \
	$(LOCAL_PATH)/S3C24XX_TouchScreen.idc:system/usr/idc/S3C24XX_TouchScreen.idc \
	$(LOCAL_PATH)/s5pc210_ts.idc:system/usr/idc/s5pc210_ts.idc \

PRODUCT_COPY_FILES += \
	frameworks/base/data/etc/handheld_core_hardware.xml:system/etc/permissions/handheld_core_hardware.xml \
	frameworks/base/data/etc/android.hardware.usb.accessory.xml:system/etc/permissions/android.hardware.usb.accessory.xml \
	packages/wallpapers/LivePicker/android.software.live_wallpaper.xml:system/etc/permissions/android.software.live_wallpaper.xml

# The OpenGL ES API level that is natively supported by this device.
# This is a 16.16 fixed point number
PRODUCT_PROPERTY_OVERRIDES := \
	ro.opengles.version=131072

PRODUCT_PROPERTY_OVERRIDES += \
	hwui.render_dirty_regions=false

# Set default USB interface
PRODUCT_DEFAULT_PROPERTY_OVERRIDES += \
	persist.sys.usb.config=mtp

#$(call inherit-product, $(PRODUCT_COMMON_DIR)/Android.mk)

ifeq ($(BOARD_USES_HIGH_RESOLUTION_LCD),true)
$(call inherit-product, frameworks/base/build/tablet-dalvik-heap.mk)

else
$(call inherit-product, frameworks/base/build/phone-hdpi-512-dalvik-heap.mk)

PRODUCT_PROPERTY_OVERRIDES += \
	ro.sf.lcd_density=240

PRODUCT_AAPT_CONFIG := normal hdpi
endif

# we have enough storage space to hold precise GC data
PRODUCT_TAGS += dalvik.gc.type-precise
